version: "3"

services:
  web:
    container_name: exampleApp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    container_name: database
    image: mongo
    ports:
      - "27018:27017"
    command: mongod --quiet --logpath /dev/null 